spring:
  application:
    name: intershop
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: ${IS_DB_URL}
    username: ${IS_DB_USERNAME}
    password: ${IS_DB_PASDWORD}
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: false
  threads:
    virtual:
      enabled: true
server:
  port: 8081
